FROM node:16-alpine
WORKDIR /usr/src/app

# ENV LANG C.UTF-8
# ENV TZ Asia/Tokyo

# ADD package.json /usr/src/app/package.json
# ADD package-lock.json /usr/src/app/package-lock.json

# RUN apt-get update -y && \
#   apt-get upgrade -y 

