version: "3.3"
services:
  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb -e production"
    volumes:
      - ./backend:/myapp
      - ./backend/vendor/bundle:/myapp/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    # ports:
    #   - "3001:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    env_file:
      - .env
    user: root

  front:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app:/usr/src/app
    command: sh -c "yarn && yarn start"
    ports:
      - "4000:3000"
    environment:
      - WDS_SOCKET_PORT=0
  
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
      - /tmp/dockerdir:/etc/mysql/conf.d/
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
  
  web:
    build:
      context: backend/containers/nginx
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - 80:80
    depends_on:
      - api

volumes:
  db:
    driver: local
  public-data:
  tmp-data:
  log-data:
  mysql-data: